//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItem
    {
        public int ID { get; set; }
        public string PurchaseID { get; set; }
        public int ItemID { get; set; }
        public string Batch { get; set; }
        public int Qty { get; set; }
        public Nullable<int> BonusIncluded { get; set; }
        public decimal CostPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public System.DateTime Expiry { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
