//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.SalesItems = new HashSet<SalesItem>();
        }
    
        public int ID { get; set; }
        public int ItemID { get; set; }
        public string BatchNo { get; set; }
        public int Qty { get; set; }
        public decimal CostPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public Nullable<System.DateTime> ManufacturedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int InitialQty { get; set; }
        public bool ItemExpired { get; set; }
        public bool Stop_Notification { get; set; }
        public string PurchaseID { get; set; }
    
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesItem> SalesItems { get; set; }
    }
}
